# Generated by Django 3.1.2 on 2020-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201026_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
