# Generated by Django 3.1.2 on 2020-10-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201026_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
    ]
