# Generated by Django 3.1.2 on 2020-10-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('startDate', models.TextField()),
                ('duration', models.TextField()),
                ('keywords', models.TextField()),
                ('categories', models.TextField()),
                ('amount', models.TextField()),
            ],
        ),
    ]
